// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	UserID    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
