services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=raden
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
